// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATH-unNNT6u6fm1cyy4j2d5B08CxkljTA',
    appId: '1:1087866382221:web:def2ce39201a77821effc4',
    messagingSenderId: '1087866382221',
    projectId: 'taskflow-7cf23',
    authDomain: 'taskflow-7cf23.firebaseapp.com',
    storageBucket: 'taskflow-7cf23.firebasestorage.app',
    measurementId: 'G-G0XHZ6HL5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb-mwTKaYlHclE0nqAWS85YH8msrcTpUY',
    appId: '1:1087866382221:android:1f158ed392e49df11effc4',
    messagingSenderId: '1087866382221',
    projectId: 'taskflow-7cf23',
    storageBucket: 'taskflow-7cf23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABMB3Nk4N4zmQ3Djwy-sN5VhBngGdJEyo',
    appId: '1:1087866382221:ios:787fa3496448ab971effc4',
    messagingSenderId: '1087866382221',
    projectId: 'taskflow-7cf23',
    storageBucket: 'taskflow-7cf23.firebasestorage.app',
    iosBundleId: 'com.taskflow.app.taskflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABMB3Nk4N4zmQ3Djwy-sN5VhBngGdJEyo',
    appId: '1:1087866382221:ios:787fa3496448ab971effc4',
    messagingSenderId: '1087866382221',
    projectId: 'taskflow-7cf23',
    storageBucket: 'taskflow-7cf23.firebasestorage.app',
    iosBundleId: 'com.taskflow.app.taskflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATH-unNNT6u6fm1cyy4j2d5B08CxkljTA',
    appId: '1:1087866382221:web:3ca24d93d0a9b6c51effc4',
    messagingSenderId: '1087866382221',
    projectId: 'taskflow-7cf23',
    authDomain: 'taskflow-7cf23.firebaseapp.com',
    storageBucket: 'taskflow-7cf23.firebasestorage.app',
    measurementId: 'G-20PPPNCRMB',
  );
}
